required = ["gopkg.in/fsnotify.v1"]

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"
